const tasks = [
  {
    "id": 101,
    "title": "Implement Login Page",
    "description": "Create a login page with authentication.",
    "status": 3,
    "priority": "High",
    "assignee": 2,
    "created_at": "2024-02-01T08:00:00Z",
    "due_date": "2024-02-10T23:59:59Z",
    "tags": ["frontend", "authentication"],
    "comments": [{ "user_id": 1, "text": "Make sure to use OAuth for authentication." }]
  },
  {
    "id": 102,
    "title": "Design User Dashboard",
    "description": "Design a user-friendly dashboard for the application.",
    "status": 1,
    "priority": "Medium",
    "assignee": 1,
    "created_at": "2024-02-02T09:00:00Z",
    "due_date": "2024-02-15T23:59:59Z",
    "tags": ["frontend", "design"],
    "comments": [{ "user_id": 3, "text": "Ensure the dashboard is responsive." }]
  },
  {
    "id": 103,
    "title": "Develop API Endpoints",
    "description": "Create RESTful API endpoints for user management.",
    "status": 3,
    "priority": "High",
    "assignee": 3,
    "created_at": "2024-02-03T10:00:00Z",
    "due_date": "2024-02-12T23:59:59Z",
    "tags": ["backend", "api"],
    "comments": [{ "user_id": 2, "text": "Use JWT for authentication." }]
  },
  {
    "id": 104,
    "title": "Write Unit Tests",
    "description": "Write unit tests for the existing codebase.",
    "status": 1,
    "priority": "Medium",
    "assignee": 2,
    "created_at": "2024-02-04T11:00:00Z",
    "due_date": "2024-02-18T23:59:59Z",
    "tags": ["testing"],
    "comments": [{ "user_id": 1, "text": "Focus on edge cases." }]
  },
  {
    "id": 105,
    "title": "Optimize Database Queries",
    "description": "Optimize the existing database queries for better performance.",
    "status": 3,
    "priority": "High",
    "assignee": 1,
    "created_at": "2024-02-05T12:00:00Z",
    "due_date": "2024-02-14T23:59:59Z",
    "tags": ["backend", "database"],
    "comments": [{ "user_id": 3, "text": "Consider indexing frequently queried fields." }]
  },
  {
    "id": 106,
    "title": "Create Admin Panel",
    "description": "Develop an admin panel for managing users and content.",
    "status": 1,
    "priority": "Medium",
    "assignee": 3,
    "created_at": "2024-02-06T13:00:00Z",
    "due_date": "2024-02-20T23:59:59Z",
    "tags": ["frontend", "admin"],
    "comments": [{ "user_id": 2, "text": "Include role-based access control." }]
  },
  {
    "id": 107,
    "title": "Implement Payment Gateway",
    "description": "Integrate a payment gateway for handling transactions.",
    "status": 3,
    "priority": "High",
    "assignee": 2,
    "created_at": "2024-02-07T14:00:00Z",
    "due_date": "2024-02-16T23:59:59Z",
    "tags": ["backend", "payment"],
    "comments": [{ "user_id": 1, "text": "Ensure PCI compliance." }]
  },
  {
    "id": 108,
    "title": "Refactor Codebase",
    "description": "Refactor the existing codebase for better maintainability.",
    "status": 1,
    "priority": "Medium",
    "assignee": 1,
    "created_at": "2024-02-08T15:00:00Z",
    "due_date": "2024-02-22T23:59:59Z",
    "tags": ["backend", "refactoring"],
    "comments": [{ "user_id": 3, "text": "Follow SOLID principles." }]
  },
  {
    "id": 109,
    "title": "Deploy Application",
    "description": "Deploy the application to the production server.",
    "status": 4,
    "priority": "High",
    "assignee": 3,
    "created_at": "2024-02-09T16:00:00Z",
    "due_date": "2024-02-17T23:59:59Z",
    "tags": ["devops", "deployment"],
    "comments": [{ "user_id": 2, "text": "Ensure zero downtime deployment." }]
  },
  {
    "id": 110,
    "title": "Monitor Application Performance",
    "description": "Set up monitoring tools to track application performance.",
    "status": 1,
    "priority": "Medium",
    "assignee": 2,
    "created_at": "2024-02-10T17:00:00Z",
    "due_date": "2024-02-24T23:59:59Z",
    "tags": ["devops", "monitoring"],
    "comments": [{ "user_id": 1, "text": "Use Prometheus and Grafana." }]
  },
  {
    "id": 111,
    "title": "Create Documentation",
    "description": "Write comprehensive documentation for the application.",
    "status": 2,
    "priority": "Medium",
    "assignee": 1,
    "created_at": "2024-02-11T18:00:00Z",
    "due_date": "2024-02-19T23:59:59Z",
    "tags": ["documentation"],
    "comments": [{ "user_id": 3, "text": "Include API reference." }]
  },
  {
    "id": 112,
    "title": "Implement Search Functionality",
    "description": "Add search functionality to the application.",
    "status": 1,
    "priority": "High",
    "assignee": 3,
    "created_at": "2024-02-12T19:00:00Z",
    "due_date": "2024-02-21T23:59:59Z",
    "tags": ["frontend", "search"],
    "comments": [{ "user_id": 2, "text": "Consider using Elasticsearch." }]
  },
  {
    "id": 113,
    "title": "Fix Bugs",
    "description": "Identify and fix bugs in the application.",
    "status": 3,
    "priority": "High",
    "assignee": 2,
    "created_at": "2024-02-13T20:00:00Z",
    "due_date": "2024-02-23T23:59:59Z",
    "tags": ["bug-fixing"],
    "comments": [{ "user_id": 1, "text": "Prioritize critical bugs." }]
  },
  {
    "id": 114,
    "title": "Upgrade Dependencies",
    "description": "Upgrade third-party dependencies to their latest versions.",
    "status": 1,
    "priority": "Medium",
    "assignee": 1,
    "created_at": "2024-02-14T21:00:00Z",
    "due_date": "2024-02-25T23:59:59Z",
    "tags": ["maintenance"],
    "comments": [{ "user_id": 3, "text": "Check for breaking changes." }]
  },
  {
    "id": 115,
    "title": "Conduct Security Audit",
    "description": "Perform a security audit to identify vulnerabilities.",
    "status": 4,
    "priority": "High",
    "assignee": 3,
    "created_at": "2024-02-15T22:00:00Z",
    "due_date": "2024-02-26T23:59:59Z",
    "tags": ["security"],
    "comments": [{ "user_id": 2, "text": "Use OWASP guidelines." }]
  },
  {
    "id": 116,
    "title": "Implement Caching",
    "description": "Add caching mechanisms to improve performance.",
    "status": 1,
    "priority": "Medium",
    "assignee": 2,
    "created_at": "2024-02-16T23:00:00Z",
    "due_date": "2024-02-27T23:59:59Z",
    "tags": ["backend", "caching"],
    "comments": [{ "user_id": 1, "text": "Consider using Redis." }]
  },
  {
    "id": 117,
    "title": "Design Email Templates",
    "description": "Create email templates for notifications and newsletters.",
    "status": 3,
    "priority": "Medium",
    "assignee": 1,
    "created_at": "2024-02-17T08:00:00Z",
    "due_date": "2024-02-28T23:59:59Z",
    "tags": ["design", "email"],
    "comments": [{ "user_id": 3, "text": "Ensure mobile responsiveness." }]
  },
  {
    "id": 118,
    "title": "Set Up CI/CD Pipeline",
    "description": "Configure a CI/CD pipeline for automated deployments.",
    "status": 1,
    "priority": "High",
    "assignee": 3,
    "created_at": "2024-02-18T09:00:00Z",
    "due_date": "2024-02-29T23:59:59Z",
    "tags": ["devops", "ci/cd"],
    "comments": [{ "user_id": 2, "text": "Use Jenkins or GitLab CI." }]
  },
  {
    "id": 119,
    "title": "Create User Guides",
    "description": "Write user guides to help users navigate the application.",
    "status": 3,
    "priority": "Medium",
    "assignee": 2,
    "created_at": "2024-02-19T10:00:00Z",
    "due_date": "2024-03-01T23:59:59Z",
    "tags": ["documentation"],
    "comments": [{ "user_id": 1, "text": "Include screenshots." }]
  },
  {
    "id": 120,
    "title": "Implement Analytics",
    "description": "Integrate analytics tools to track user behavior.",
    "status": 1,
    "priority": "High",
    "assignee": 1,
    "created_at": "2024-02-20T11:00:00Z",
    "due_date": "2024-03-02T23:59:59Z",
    "tags": ["analytics"],
    "comments": [{ "user_id": 3, "text": "Use Google Analytics or Mixpanel." }]
  },
  {
    "id": 121,
    "title": "Optimize Frontend Performance",
    "description": "Optimize the frontend code for faster load times.",
    "status": 3,
    "priority": "High",
    "assignee": 3,
    "created_at": "2024-02-21T12:00:00Z",
    "due_date": "2024-03-03T23:59:59Z",
    "tags": ["frontend", "performance"],
    "comments": [{ "user_id": 2, "text": "Minify CSS and JS files." }]
  },
  {
    "id": 122,
    "title": "Conduct User Testing",
    "description": "Organize user testing sessions to gather feedback.",
    "status": 2,
    "priority": "Medium",
    "assignee": 2,
    "created_at": "2024-02-22T13:00:00Z",
    "due_date": "2024-03-04T23:59:59Z",
    "tags": ["testing", "user-feedback"],
    "comments": [{ "user_id": 1, "text": "Prepare a feedback form." }]
  },
  {
    "id": 123,
    "title": "Implement Localization",
    "description": "Add support for multiple languages in the application.",
    "status": 3,
    "priority": "Medium",
    "assignee": 1,
    "created_at": "2024-02-23T14:00:00Z",
    "due_date": "2024-03-05T23:59:59Z",
    "tags": ["frontend", "localization"],
    "comments": [{ "user_id": 3, "text": "Use i18n library." }]
  },
  {
    "id": 124,
    "title": "Create Backup Strategy",
    "description": "Develop a backup strategy for data protection.",
    "status": 1,
    "priority": "High",
    "assignee": 3,
    "created_at": "2024-02-24T15:00:00Z",
    "due_date": "2024-03-06T23:59:59Z",
    "tags": ["devops", "backup"],
    "comments": [{ "user_id": 2, "text": "Consider daily backups." }]
  },
  {
    "id": 125,
    "title": "Implement Push Notifications",
    "description": "Add push notification functionality to the application.",
    "status": 3,
    "priority": "Medium",
    "assignee": 2,
    "created_at": "2024-02-25T16:00:00Z",
    "due_date": "2024-03-07T23:59:59Z",
    "tags": ["frontend", "notifications"],
    "comments": [{ "user_id": 1, "text": "Use Firebase Cloud Messaging." }]
  },
  {
    "id": 126,
    "title": "Design Mobile App",
    "description": "Create a design for the mobile version of the application.",
    "status": 1,
    "priority": "High",
    "assignee": 1,
    "created_at": "2024-02-26T17:00:00Z",
    "due_date": "2024-03-08T23:59:59Z",
    "tags": ["design", "mobile"],
    "comments": [{ "user_id": 3, "text": "Follow Material Design guidelines." }]
  },
  {
    "id": 127,
    "title": "Develop Mobile App",
    "description": "Build the mobile application based on the design.",
    "status": 3,
    "priority": "High",
    "assignee": 3,
    "created_at": "2024-02-27T18:00:00Z",
    "due_date": "2024-03-09T23:59:59Z",
    "tags": ["mobile", "development"],
    "comments": [{ "user_id": 2, "text": "Use React Native for cross-platform development." }]
  },
  {
    "id": 128,
    "title": "Test Mobile App",
    "description": "Conduct testing on the mobile application.",
    "status": 1,
    "priority": "Medium",
    "assignee": 2,
    "created_at": "2024-02-28T19:00:00Z",
    "due_date": "2024-03-10T23:59:59Z",
    "tags": ["testing", "mobile"],
    "comments": [{ "user_id": 1, "text": "Test on both iOS and Android." }]
  },
  {
    "id": 129,
    "title": "Deploy Mobile App",
    "description": "Deploy the mobile application to app stores.",
    "status": 3,
    "priority": "High",
    "assignee": 1,
    "created_at": "2024-02-29T20:00:00Z",
    "due_date": "2024-03-11T23:59:59Z",
    "tags": ["mobile", "deployment"],
    "comments": [{ "user_id": 3, "text": "Follow app store guidelines." }]
  },
  {
    "id": 130,
    "title": "Monitor Mobile App Performance",
    "description": "Set up monitoring for the mobile application.",
    "status": 1,
    "priority": "Medium",
    "assignee": 3,
    "created_at": "2024-03-01T21:00:00Z",
    "due_date": "2024-03-12T23:59:59Z",
    "tags": ["mobile", "monitoring"],
    "comments": [{ "user_id": 2, "text": "Use Crashlytics for crash reporting." }]
  },
  {
    "id": 131,
    "title": "Gather User Feedback",
    "description": "Collect feedback from users to improve the application.",
    "status": 3,
    "priority": "Medium",
    "assignee": 2,
    "created_at": "2024-03-02T22:00:00Z",
    "due_date": "2024-03-13T23:59:59Z",
    "tags": ["user-feedback"],
    "comments": [{ "user_id": 2, "text": "Use Crashlytics for crash reporting." }]
  }
]

export default tasks;